### ISSUE TITLE
Fix github CI

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#154]
[Python 3.6 doesn't seem to work with the Ubuntu github actions runners](https://github.com/actions/setup-python/issues/544#issuecomment-1332535877) because it's no longer supported. So deprecate Python 3.6 and remove it from CI. Also, validate that we aren't using 3.6 anywhere. Currently tap serves using Python 3.9.

**Comment by potatoboiler** [comment]
#155
