### ISSUE TITLE
Newuser confirmation email

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#37]
Send an email when a user's email is create. Also, send a copy to outreach so that they can welcome them

**Comment by wylliec** [comment]
pretty sure mailman already does this when a user gets signed up for csua-newmembers

**Comment by robertquitt** [comment]
> pretty sure mailman already does this when a user gets signed up for csua-newmembers

This is correct, but mailman was broken for a long time (from around March 2019 to November 2019) due to a bug related to enforcing TLS from postfix, causing mailman not to be able to send any emails.
