### ISSUE TITLE
Newuser is broken

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#46]
The same UID is being used when creating a new user. See the following:

```
nikhilushinde:x:31934:1000:FIRST LAST,poop@berkeley.edu:/home/nikhilushinde:/bin/bash
khangly:x:31935:1000:FIRST LAST,poop@berkeley.edu:/home/khangly:/bin/bash
SPak12:x:31935:1000:FIRST LAST,poop@berkeley.edu:/home/SPak12:/bin/bash
cmoore15:x:31935:1000:FIRST LAST,poop@berkeley.edu:/home/cmoore15:/bin/bash
jxlin:x:31935:1000:John FIRST LAST,poop@berkeley.edu:/home/jxlin:/bin/bash
kazu:x:31935:1000:FIRST LAST,poop@berkeley.edu:/home/kazu:/bin/bash
fenptg:x:31935:1000:FIRST LAST,poop@berkeley.edu:/home/fenptg:/bin/bash
```

**Comment by robertquitt** [comment]
A temporary fix is to manually change the UIDs in LDAP by by using `sudo ldapvi -D (uid=robertq)`, then reset `nscd` caches with  `sudo nscd -i passwd`, then fix the file permissions on the home directories `sudo chown -R kazu ~kazu`

**Comment by abizer** [comment]
you may want to redact those email addresses

**Comment by robertquitt** [comment]
> you may want to redact those email addresses

Thanks, silly mistake. They are still visible if you know how to access our LDAP server though.

**Comment by abizer** [comment]
get you a firewall or make the mail attribute one that requires an authenticated/privileged bind
