### ISSUE TITLE
Assign LDAP groups to Django User groups

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#47]
As part of #19. This way permissions on the site can be reasonably managed, especially as "officer-only" and "pb-only" views/actions are being added.

**Comment by mark64** [comment]
What does this mean? Is the idea that we would authenticate in Django via LDAP when doing `pb-only` actions, rather than using credentials in the django db?

**Comment by robertquitt** [comment]
> Is the idea that we would authenticate in Django via LDAP when doing pb-only actions, rather than using credentials in the django db?

This is already happening--currently, logging into the website will check LDAP for a matching user and password then check the db backend.
```python
AUTHENTICATION_BACKENDS = [
    "django_python3_ldap.auth.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]
```
What I mean here is how _group membership_ should be handled. Somehow we need to distinguish a user as being "in officers" and "not in officers" group, among other things. Currently, we simply make an ldap query. The question is, should we store this membership in the django database or query LDAP every time?

Clarification aside, I think it's fine to query LDAP every time we need to make a group membership check.

**Comment by robertquitt** [comment]
https://github.com/CSUA/csua-backend/blob/77a43641cb93c2d3f43da0f47d904669faf25424/apps/ldap/utils.py#L96

We can use this to check group membership, no need to populate the database. This is a bit slower than making a query, but it should be negligible.
