### ISSUE TITLE
Add links to other clubs!

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#68]
CSUA works with other clubs on campus to host events and more, it would be nice to link to their webpages from ours. On the bottom of the homepage, next to the department columns we could add another that links to other clubs such as but not limited to XR@B, ML@B, HKN, UPE, SWE, AWE

**Comment by robertquitt** [comment]
@rhu2001 will work on this on his fork

**Comment by rhu2001** [comment]
Comment
