### ISSUE TITLE
Remote Newuser Form

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#69]
Currently, the newuser form has to be filled out in person with an officer's approval. We should add the option to fill out the newuser form remotely. Especially considering the COVID/remote situation, this would allow us to continue to bring in new users without having to have an officer fill out the form with them.

## User flow (proposed)

1. Click a visible button that says "create new account"
2. User fills in berkeley email, SID, desired username, password, agree to rules, consent to emails
  - Possibly also add some "fun questions" like "Reverse a linked list" or "Name a downside of Java" or "write a function that returns true if the input function halts"
3. User confirms their berkeley email via a link
  - Possible have the user wait for an officer to accept a pending user creation request

**Comment by samsafadi** [comment]
A possible easier implementation would be to just use a small passcode that is sent to them and entered into the static page, meaning you enter your Berkeley email, the page switches to asking for a 5 digit pin code that's randomly generated, then the user enters it which reveals the rest of the newuser form.

**Comment by robertquitt** [comment]
Completed and merged into master
