### ISSUE TITLE
Adding officer app link into join page 

### ISSUE THREAD

**Issue by kuhusharma** [CSUA/csua-backend#80]
Unable to test this rn bc ssh is being mean, but TLDR is instead of 

"If you would like to become an officer, please email the politburo at pb@csua.berkeley.edu to get the application form."

we have 
"If you would like to become an officer, please fill out this form" where this form links to [csua.berkeley.edu/officerapp](url) (so that we can change it every semester without having to update html) 

in templates/join.html

**Comment by aninrusimha** [comment]
Addressed in #82 #83
